# TermGreet Example Configuration
# Copy this file to ~/.config/termgreet/config.toml and modify it as needed

# General settings
[general]
title = "System Information"

# Separator configuration between module names and values
[general.separator]
symbol = "->"        # The separator character/string (e.g., "->", ":", "=", "|")
space_before = 2     # Number of spaces before the separator
space_after = 6     # Number of spaces after the separator
align_separator = true  # Align all separators in a column by padding module names

# Color configuration
[general.colors]
# Available colors:
#  "black"
#  "red"
#  "green"
#  "yellow"
#  "blue"
#  "magenta"
#  "cyan"
#  "white"
#  "bright_black"
#  "bright_red"
#  "bright_green"
#  "bright_yellow"
#  "bright_blue"
#  "bright_magenta"
#  "bright_cyan"
#  "bright_white"
title = "bright_cyan"     # Color for the main title (e.g., "System Information")
module = "bright_cyan"    # Color for module names (e.g., "OS", "Kernel", "CPU")
info = "bright_white"     # Color for the information values
separator = "bright_blue" # Color for the separator between module and value

[display]
show_image = true
image_path = "~/Pictures/khrom_small.png"  # Path to your PNG image
prefer_kitty_graphics = true  # true = prefer Kitty Protocol, false = force block-rendering fallback
padding = 2
layout = "vertical"  # "vertical" or "horizontal"

[display.image_size]
width = 35
height = 15
cell_width = 17   # Pixels per terminal character (width) - adjust for perfect aspect ratio
cell_height = 24  # Pixels per terminal character (height) - adjust for perfect aspect ratio

[display.block_rendering]                      # use this if kitty_graphics is false
block_style = "default"                        # Block character style: "default", "ascii", "braille", "custom"
custom_blocks = ["█", "▓", "▒", "░", " "]      # Custom block characters (used when block_style = "custom")
brightness_thresholds = [0.8, 0.6, 0.3, 0.1]   # Brightness thresholds for block selection (0.0-1.0)
color_mode = "truecolor"                       # Color mode: "truecolor", "256color", "16color", "monochrome"
contrast = 1.0                                 # Contrast adjustment (0.5-2.0)
brightness_boost = 0.0                         # Brightness boost (-0.5 to +0.5)
sampling_method = "dominant"                   # Sampling method: "average", "dominant", "weighted"
enable_dithering = true                        # Enable dithering for better quality

[modules]
show_versions = true  # Show version information for Shell, Terminal, DE, WM modules
user_at_host = true
os = true
kernel = true
linux = false
uptime = true
os_age = true
packages = true
flatpak_packages = false
packages_combined = false
shell = true
resolution = true
de = false
wm = false
theme = false
icons = false
terminal = true
font = true
user = false
hostname = false
cpu = true
cpu_temp = true
gpu = true
gpu_temp = true
gpu_driver = true
memory = true
disk = true
battery = true
locale = false

[modules.display_names]
# Custom display names for modules
# If not specified, default names will be used
# Text-only examples (recommended for universal compatibility):
user_at_host = "System"      # Default: "Login"
os = "Operating System"      # Default: "OS"
kernel = "Kernel"             # Default: "Kernel"
uptime = "Uptime"             # Default: "Uptime"
os_age = "OS Age"             # Default: "OS Age"
packages = "Packages"         # Default: "Packages"
shell = "Shell"               # Default: "Shell"
resolution = "Resolution"     # Default: "Resolution"
terminal = "Terminal"         # Default: "Terminal"
font = "Font"                # Default: "Font"
cpu = "Processor"            # Default: "CPU"
cpu_temp = "CPU Temperature"   # Default: "CPU Temp"
gpu = "Graphics"             # Default: "GPU"
gpu_temp = "GPU Temperature"   # Default: "GPU Temp"
gpu_driver = "GPU Driver"     # Default: "GPU Driver"
memory = "Sys. Mem."             # Default: "Memory"
disk = "Storage"             # Default: "Disk"
# Optional: Add Nerd Font icons if your terminal/font supports them:
# user_at_host = " System"  # Nerd Font icon examples
# cpu = " Processor"
# Or leave fields commented out to use defaults

# Enable or disable MOTD display
show_motd = true

# Path to MOTD configuration file
motd_file = "~/.config/termgreet/motd.toml"
