# TermGreet Beispiel-Konfiguration
# Kopieren Sie diese Datei nach ~/.config/termgreet/config.toml und passen Sie sie an

[general]
title = "System Information"
separator = " -> "

[general.colors]
title = "bright_cyan"
info = "bright_white"
separator = "bright_blue"

[display]
show_image = true
image_path = "~/Bilder/khrom_small.png"  # Pfad zu Ihrem PNG-Bild
prefer_kitty_graphics = true  # true = Kitty Protocol bevorzugt, false = viuer erzwingen
padding = 2

[display.image_size]
width = 35
height = 15
cell_width = 17     # Pixel pro Terminal-Zeichen (Breite) - für Ghostty/Kitty evtl. 8-12
cell_height = 24    # Pixel pro Terminal-Zeichen (Höhe) - für Ghostty/Kitty evtl. 16-24

[modules]
os = true
kernel = true
uptime = true
os_age = true
packages = true
shell = true
resolution = true
de = true
wm = true
theme = false
icons = false
terminal = true
cpu = true
gpu = true
memory = true
disk = true
battery = true
locale = false

# Pfad zur MOTD-Konfigurationsdatei
motd_file = "~/.config/termgreet/motd.toml"
