# TermGreet Example Configuration
# Copy this file to ~/.config/termgreet/config.toml and modify it as needed

# General settings
[general]
title = "System Information"

# Separator configuration between module names and values
[general.separator]
symbol = "->"        # The separator character/string (e.g., "->", ":", "=", "|")
space_before = 2     # Number of spaces before the separator
space_after = 6     # Number of spaces after the separator
align_separator = true  # Align all separators in a column by padding module names

# Color configuration
[general.colors]
# Available colors:
#  "black"
#  "red"
#  "green"
#  "yellow"
#  "blue"
#  "magenta"
#  "cyan"
#  "white"
#  "bright_black"
#  "bright_red"
#  "bright_green"
#  "bright_yellow"
#  "bright_blue"
#  "bright_magenta"
#  "bright_cyan"
#  "bright_white"
title = "bright_cyan"     # Color for the main title (e.g., "System Information")
module = "bright_cyan"    # Color for module names (e.g., "OS", "Kernel", "CPU")
info = "bright_white"     # Color for the information values
separator = "bright_blue" # Color for the separator between module and value

[display]
show_image = true
image_path = "~/Pictures/khrom_small.png"  # Path to your PNG image
prefer_kitty_graphics = true  # true = prefer Kitty Protocol, false = force viuer fallback
padding = 2

[display.image_size]
width = 35
height = 15
cell_width = 17     # Pixels per terminal character (width)
cell_height = 24    # Pixels per terminal character (height)

[modules]
os = true
kernel = true
uptime = true
os_age = true
packages = true
shell = true
resolution = true
de = true
wm = true
theme = false
icons = false
terminal = true
cpu = true
gpu = true
memory = true
disk = true
battery = true
locale = false

# Enable or disable MOTD display
show_motd = true

# Path to MOTD configuration file
motd_file = "~/.config/termgreet/motd.toml"
